---
title: Community network plots
author: Gibran Hemani
data: 25/02/2019
---

```{r}
library(knitr)
opts_chunk$set(cache=FALSE, echo=TRUE, message=FALSE, warning=FALSE)
```

```{r}
library(LOLA)
library(dplyr)
library(data.table)
library(reshape2)
library(GenomicRanges)
library(parallel)
# Get communities of interest


tfbsdb <- loadRegionDB("../../data/lola/scratch/ns5bc/resources/regions/LOLACore/hg19")
load("../results/core_communities_cpg_tophits.rdata")
# load("../results/communities.rdata")
load("../results/lola_snp_communities.rdata")
load("../data/lola/cpg_granges.rdata")
load("../data/lola/snp_granges.rdata")
load("../results/graph.rdata")
load("../data/grinfo.rdata")

# load("../../11_2d-enrichments/data/annotations.rdata")
```


1. Get top Community annotations
2. Get CpGs that are in those communities that have those annotations
3. Get SNPs that influence those CpGs
4. Get annotations for those SNPs


Parts 1 and 2:

```{r}
userSet <- "userSet"
temp <- rbind(
	data_frame(cpg=dat$creg, snp=dat$snp, cpg_chr=dat$creg_chr, cpg_pos=dat$creg_pos, cis=TRUE),
	data_frame(cpg=dat$tcpg, snp=dat$snp, cpg_chr=dat$tcpg_chr, cpg_pos=dat$tcpg_pos, cis=FALSE)
) %>%
filter(!duplicated(paste(cpg, snp)))

l <- mclapply(1:nrow(core_communities_cpg_tophits), function(i) {
	message(i)
	out <- extractEnrichmentOverlaps(as.data.frame(core_communities_cpg_tophits)[i,], community_cpgs_separate, tfbsdb) %>% as.data.frame
	out <- subset(temp, 
			paste(cpg_chr, cpg_pos) %in% paste(out$seqnames, out$start)
		) %>%
	filter(!duplicated(paste(cpg, snp)))
	out$userSet <- core_communities_cpg_tophits$userSet[i]
	out <- merge(out, as.data.frame(core_communities_cpg_tophits)[i,])
	return(out)
}, mc.cores=10)

out <- bind_rows(l)
out$antibody[is.na(out$antibody)] <- out$description[is.na(out$antibody)]

ind <- grepl("CTCF", out$antibody)
out$antibody[ind] <- "CTCF"
ind <- grepl("SMC3", out$antibody)
out$antibody[ind] <- "SMC3"
ind <- grepl("Znf143", out$antibody)
out$antibody[ind] <- "Znf143"
out$antibody <- toupper(out$antibody)

out2 <- out %>%
	arrange(desc(pValueLog), cpg, antibody) %>%
	group_by(userSet, cpg, antibody) %>%
	mutate(count=n()) %>%
	filter(!duplicated(paste(userSet, cpg, antibody)))
glimpse(out)
```


### SNP annotations

```{r}
xsnps <- subset(grinfo, snp %in% unique(out$snp) & !duplicated(snp))
nom <- xsnps$snp
xsnps <- GRanges(seqnames=xsnps$snpchr, IRanges(xsnps$min, xsnps$max))
names(xsnps) <- nom

snpo <- lapply(tfbsdb$regionGRL, function(x){
	xsnps[queryHits(findOverlaps(xsnps, x))]
})

snpo2 <- list()
for(i in 1:length(snpo))
{
	if(length(snpo[[i]]) > 0)
	{
		x <- snpo[[i]][!duplicated(names(snpo[[i]]))]
		snpo2[[i]] <- as.data.frame(x)
		snpo2[[i]]$ind <- i
	}
}
snpo2 <- bind_rows(snpo2)
snpo2 <- cbind(snpo2, temp[snpo2$ind, ])
glimpse(snpo2)

temp <- tfbsdb[[2]]
subset(temp, collection == "encode_tfbs" & cellType == "HFF")

m <- mclapply(1:nrow(out), function(i)
{
	message(i)
	ind <- which(temp$collection == out$collection[i] & temp$cellType == out$cellType[i])
	message(length(ind))
	n <- list()
	for(j in 1:length(ind))
	{
		temp2 <- tfbsdb$regionGRL[[ind[j]]]
		temp3 <- xsnps[names(xsnps) == out$snp[i]]
		temp3[queryHits(findOverlaps(temp3, temp2))]
		if(length(temp) > 0)
		{
			ret <- temp[ind[j], ]
			ret$snp <- names(temp3)
			n[[j]] <- ret
		}
	}
	return(bind_rows(n))
}, mc.cores=10)
glimpse(m[1:5])
```

Save:

```{r}
save(snpo2, out, m, file="../results/plotting_community_enrichments.rdata")
```

