import os
os.makedirs("../data", exist_ok=True)


rule all:
	input: "../data/coloc_results.rdata"

rule generate_ld_matrices:
	input: "../../data/ldetect/EUR.bed", "../../data/ref/out_hrc.bed"
	output: "../data/ld.rdata"
	shell:
		"Rscript generate_ld_matrices.r"

rule simulation:
	input: "../data/ld.rdata", "simulation.r"
	output: "../data/coloc_results.rdata"
	shell:
		"Rscript simulation.r"
