rule all:
	input: "../data/coloc_results.rdata"

rule generate_ld_matrices:
	input: "../../data/ldetect/EUR.bed", "../../data/ref/out_hrc.bed"
	output: "../data/ld.rdata"
	script:
		"Rscript generate_ld_matrices.r"

rule simulation
	input: "../data/ld.rdata", "simulation.r"
	output: "../data/coloc_results.rdata"
	script:
		"Rscript simulation.r"
