##	first	argument	is	name	of	"trait,"	second	argument	is	folder	name	where	results	are
														
./garfield-v2-GCcorrection.sh	ADHD	ADHD																							
./garfield-v2-GCcorrection.sh	AcAce	AcAce												
./garfield-v2-GCcorrection.sh	Ace	Ace												
./garfield-v2-GCcorrection.sh	AD_Stage1	AD_Stage1												
./garfield-v2-GCcorrection.sh	AD_Stage1_2Combined	AD_Stage1_2Combined												
./garfield-v2-GCcorrection.sh	ADHD	ADHD												
./garfield-v2-GCcorrection.sh	AIR	AIR												
./garfield-v2-GCcorrection.sh	AIR_adj_BMI+SI	AIR_adj_BMI+SI												
./garfield-v2-GCcorrection.sh	AIR_adj_SII	AIR_adj_SII												
./garfield-v2-GCcorrection.sh	Ala	Ala												
./garfield-v2-GCcorrection.sh	Alb	Alb												
./garfield-v2-GCcorrection.sh	ALS	ALS_LMM												
./garfield-v2-GCcorrection.sh	ALS	ALS_Meta												
./garfield-v2-GCcorrection.sh	ALS_lmm	ALS_lmm												
./garfield-v2-GCcorrection.sh	ALS_meta	ALS_meta												
./garfield-v2-GCcorrection.sh	Alzheimers	Alzheimers												
./garfield-v2-GCcorrection.sh	Anorexia	Anorexia												
./garfield-v2-GCcorrection.sh	Anorexia	Anorexia												
./garfield-v2-GCcorrection.sh	Anorexia	Anorexia												
./garfield-v2-GCcorrection.sh	Anorexia	Anorexia												
./garfield-v2-GCcorrection.sh	ApoA1	ApoA1												
./garfield-v2-GCcorrection.sh	ApoB	ApoB												
./garfield-v2-GCcorrection.sh	ApoptoticDermatitis	ECZEMA												
./garfield-v2-GCcorrection.sh	Asthma	Asthma												
./garfield-v2-GCcorrection.sh	Autism_lmm	Autism_lmm												
./garfield-v2-GCcorrection.sh	Autism_Mar2016	Autism_Mar2016												
./garfield-v2-GCcorrection.sh	Autism_Mar2016	Autism_Mar2016												
./garfield-v2-GCcorrection.sh	BipolarDisorder	BipolarDisorder												
./garfield-v2-GCcorrection.sh	Bis.DB.ratio	Bis.DB.ratio												
./garfield-v2-GCcorrection.sh	Bis.FA.ratio	Bis.FA.ratio												
./garfield-v2-GCcorrection.sh	BMI_Locke	BMI_Locke												
./garfield-v2-GCcorrection.sh	bOHBut	bOHBut												
./garfield-v2-GCcorrection.sh	BPD	BPD												
./garfield-v2-GCcorrection.sh	Cardiogram_2	Cardiogram_2												
./garfield-v2-GCcorrection.sh	CH2.DB.ratio	CH2.DB.ratio												
./garfield-v2-GCcorrection.sh	CH2.in.FA	CH2.in.FA												
./garfield-v2-GCcorrection.sh	Chronotype	Chronotype												
./garfield-v2-GCcorrection.sh	Cit	Cit												
./garfield-v2-GCcorrection.sh	CKD	CKD												
./garfield-v2-GCcorrection.sh	CollegeCompletion	CollegeCompletion												
./garfield-v2-GCcorrection.sh	CoronaryArteryDisease	CAD_2014												
./garfield-v2-GCcorrection.sh	CPD	CPD												
./garfield-v2-GCcorrection.sh	Crea	Crea												
./garfield-v2-GCcorrection.sh	DB.in.FA	DB.in.FA												
./garfield-v2-GCcorrection.sh	DHA	DHA												
./garfield-v2-GCcorrection.sh	DI	DI												
./garfield-v2-GCcorrection.sh	DI_adj_BMI	DI_adj_BMI												
./garfield-v2-GCcorrection.sh	DS	DS												
./garfield-v2-GCcorrection.sh	EAGLE_AD	EAGLE_AD												
./garfield-v2-GCcorrection.sh	EduYears	EduYears												
./garfield-v2-GCcorrection.sh	EduYearsMain	EduYearsMain												
./garfield-v2-GCcorrection.sh	eGFRcrea_overall	eGFRcrea_overall												
./garfield-v2-GCcorrection.sh	eGFRcys_overall	eGFRcys_overall												
./garfield-v2-GCcorrection.sh	EGG	EGG												
./garfield-v2-GCcorrection.sh	EGG_BL	EGG_BL												
./garfield-v2-GCcorrection.sh	EnigmaAccumbens	EnigmaAccumbens												
./garfield-v2-GCcorrection.sh	EnigmaAmygdala	EnigmaAmygdala												
./garfield-v2-GCcorrection.sh	EnigmaCaudate	EnigmaCaudate												
./garfield-v2-GCcorrection.sh	EnigmaHippocampus	EnigmaHippocampus												
./garfield-v2-GCcorrection.sh	EnigmaICV	EnigmaICV												
./garfield-v2-GCcorrection.sh	EnigmaPallidum	EnigmaPallidum												
./garfield-v2-GCcorrection.sh	EnigmaPutamen	EnigmaPutamen												
./garfield-v2-GCcorrection.sh	EnigmaThalamus	EnigmaThalamus												
./garfield-v2-GCcorrection.sh	Est.C	Est.C												
./garfield-v2-GCcorrection.sh	EverSmoked	EverSmoked												
./garfield-v2-GCcorrection.sh	EXTREME_BMI	EXTREME_BMI												
./garfield-v2-GCcorrection.sh	EXTREME_HEIGHT	EXTREME_HEIGHT												
./garfield-v2-GCcorrection.sh	EXTREME_WHR	EXTREME_WHR												
./garfield-v2-GCcorrection.sh	FALen	FALen												
./garfield-v2-GCcorrection.sh	father_age_death	father_age_death												
./garfield-v2-GCcorrection.sh	FAw3	FAw3												
./garfield-v2-GCcorrection.sh	FAw6	FAw6												
./garfield-v2-GCcorrection.sh	FAw79S	FAw79S												
./garfield-v2-GCcorrection.sh	Free.C	Free.C												
./garfield-v2-GCcorrection.sh	Glc	Glc												
./garfield-v2-GCcorrection.sh	Gln	Gln												
./garfield-v2-GCcorrection.sh	Glol	Glol												
./garfield-v2-GCcorrection.sh	Gly	Gly												
./garfield-v2-GCcorrection.sh	Gp	Gp												
./garfield-v2-GCcorrection.sh	HDL	HDL												
./garfield-v2-GCcorrection.sh	HDL.C	HDL.C												
./garfield-v2-GCcorrection.sh	HDL.D	HDL.D												
./garfield-v2-GCcorrection.sh	Height	GIANT_HEIGHT												
./garfield-v2-GCcorrection.sh	HIP	HIP												
./garfield-v2-GCcorrection.sh	His	His												
./garfield-v2-GCcorrection.sh	HR	HR												
./garfield-v2-GCcorrection.sh	IBD	IBD												
./garfield-v2-GCcorrection.sh	IBD_CD	IBD_CD												
./garfield-v2-GCcorrection.sh	IBD_UC	IBD_UC												
./garfield-v2-GCcorrection.sh	IDL.C	IDL.C												
./garfield-v2-GCcorrection.sh	IDL.FC	IDL.FC												
./garfield-v2-GCcorrection.sh	IDL.L	IDL.L												
./garfield-v2-GCcorrection.sh	IDL.P	IDL.P												
./garfield-v2-GCcorrection.sh	IDL.PL	IDL.PL												
./garfield-v2-GCcorrection.sh	IDL.TG	IDL.TG												
./garfield-v2-GCcorrection.sh	Ile	Ile												
./garfield-v2-GCcorrection.sh	ISR	ISR												
./garfield-v2-GCcorrection.sh	ISR_adj_BMI	ISR_adj_BMI												
./garfield-v2-GCcorrection.sh	L.HDL.C	L.HDL.C												
./garfield-v2-GCcorrection.sh	L.HDL.CE	L.HDL.CE												
./garfield-v2-GCcorrection.sh	L.HDL.FC	L.HDL.FC												
./garfield-v2-GCcorrection.sh	L.HDL.L	L.HDL.L												
./garfield-v2-GCcorrection.sh	L.HDL.P	L.HDL.P												
./garfield-v2-GCcorrection.sh	L.HDL.PL	L.HDL.PL												
./garfield-v2-GCcorrection.sh	L.LDL.C	L.LDL.C												
./garfield-v2-GCcorrection.sh	L.LDL.CE	L.LDL.CE												
./garfield-v2-GCcorrection.sh	L.LDL.FC	L.LDL.FC												
./garfield-v2-GCcorrection.sh	L.LDL.L	L.LDL.L												
./garfield-v2-GCcorrection.sh	L.LDL.P	L.LDL.P												
./garfield-v2-GCcorrection.sh	L.LDL.PL	L.LDL.PL												
./garfield-v2-GCcorrection.sh	L.VLDL.C	L.VLDL.C												
./garfield-v2-GCcorrection.sh	L.VLDL.CE	L.VLDL.CE												
./garfield-v2-GCcorrection.sh	L.VLDL.FC	L.VLDL.FC												
./garfield-v2-GCcorrection.sh	L.VLDL.L	L.VLDL.L												
./garfield-v2-GCcorrection.sh	L.VLDL.P	L.VLDL.P												
./garfield-v2-GCcorrection.sh	L.VLDL.PL	L.VLDL.PL												
./garfield-v2-GCcorrection.sh	L.VLDL.TG	L.VLDL.TG												
./garfield-v2-GCcorrection.sh	LA	LA												
./garfield-v2-GCcorrection.sh	Lac	Lac												
./garfield-v2-GCcorrection.sh	LDL	LDL												
./garfield-v2-GCcorrection.sh	LDL.C	LDL.C												
./garfield-v2-GCcorrection.sh	LDL.D	LDL.D												
./garfield-v2-GCcorrection.sh	LeptinAdjBMI	LeptinAdjBMI												
./garfield-v2-GCcorrection.sh	LeptinNotAdjBMI	LeptinNotAdjBMI												
./garfield-v2-GCcorrection.sh	Leu	Leu												
./garfield-v2-GCcorrection.sh	M.HDL.C	M.HDL.C												
./garfield-v2-GCcorrection.sh	M.HDL.CE	M.HDL.CE												
./garfield-v2-GCcorrection.sh	M.HDL.FC	M.HDL.FC												
./garfield-v2-GCcorrection.sh	M.HDL.L	M.HDL.L												
./garfield-v2-GCcorrection.sh	M.HDL.P	M.HDL.P												
./garfield-v2-GCcorrection.sh	M.HDL.PL	M.HDL.PL												
./garfield-v2-GCcorrection.sh	M.LDL.C	M.LDL.C												
./garfield-v2-GCcorrection.sh	M.LDL.CE	M.LDL.CE												
./garfield-v2-GCcorrection.sh	M.LDL.L	M.LDL.L												
./garfield-v2-GCcorrection.sh	M.LDL.P	M.LDL.P												
./garfield-v2-GCcorrection.sh	M.LDL.PL	M.LDL.PL												
./garfield-v2-GCcorrection.sh	M.VLDL.C	M.VLDL.C												
./garfield-v2-GCcorrection.sh	M.VLDL.CE	M.VLDL.CE												
./garfield-v2-GCcorrection.sh	M.VLDL.FC	M.VLDL.FC												
./garfield-v2-GCcorrection.sh	M.VLDL.L	M.VLDL.L												
./garfield-v2-GCcorrection.sh	M.VLDL.P	M.VLDL.P												
./garfield-v2-GCcorrection.sh	M.VLDL.PL	M.VLDL.PL												
./garfield-v2-GCcorrection.sh	M.VLDL.TG	M.VLDL.TG												
./garfield-v2-GCcorrection.sh	MDD	MDD												
./garfield-v2-GCcorrection.sh	Menopause	Menopause												
./garfield-v2-GCcorrection.sh	meta_European_v2_SMRFormat.txt	meta_European_v2_SMRFormat.txt												
./garfield-v2-GCcorrection.sh	Migraine	Migraine												
./garfield-v2-GCcorrection.sh	mother_age_death	mother_age_death												
./garfield-v2-GCcorrection.sh	MUFA	MUFA												
./garfield-v2-GCcorrection.sh	MyocardialInfarction	MI_2015												
./garfield-v2-GCcorrection.sh	NeurotiGCcorrectionm	NeurotiGCcorrectionm												
./garfield-v2-GCcorrection.sh	ObesityClass1	ObesityClass1												
./garfield-v2-GCcorrection.sh	ObesityClass2	ObesityClass2												
./garfield-v2-GCcorrection.sh	ObesityClass3	ObesityClass3												
./garfield-v2-GCcorrection.sh	otPUFA	otPUFA												
./garfield-v2-GCcorrection.sh	Overweight	Overweight												
./garfield-v2-GCcorrection.sh	parents_age_death	parents_age_death												
./garfield-v2-GCcorrection.sh	PC	PC												
./garfield-v2-GCcorrection.sh	PEAK	PEAK												
./garfield-v2-GCcorrection.sh	PEAK_adj_BMI+SI	PEAK_adj_BMI+SI												
./garfield-v2-GCcorrection.sh	PEAK_adj_SI	PEAK_adj_SI												
./garfield-v2-GCcorrection.sh	Phe	Phe												
./garfield-v2-GCcorrection.sh	Pubertal_growth_10F	Pubertal_growth_10F												
./garfield-v2-GCcorrection.sh	Pubertal_growth_10F_12M_combined	Pubertal_growth_10F_12M_combined												
./garfield-v2-GCcorrection.sh	Pubertal_growth_12M	Pubertal_growth_12M												
./garfield-v2-GCcorrection.sh	Pubertal_growth_PGF	Pubertal_growth_PGF												
./garfield-v2-GCcorrection.sh	Pubertal_growth_PGF_PGM_combined	Pubertal_growth_PGF_PGM_combined												
./garfield-v2-GCcorrection.sh	Pubertal_growth_PGM	Pubertal_growth_PGM												
./garfield-v2-GCcorrection.sh	Pubertal_growth_PTF	Pubertal_growth_PTF												
./garfield-v2-GCcorrection.sh	Pubertal_growth_PTF_PTM_combined	Pubertal_growth_PTF_PTM_combined												
./garfield-v2-GCcorrection.sh	Pubertal_growth_PTM	Pubertal_growth_PTM												
./garfield-v2-GCcorrection.sh	Pyr	Pyr												
./garfield-v2-GCcorrection.sh	S.HDL.L	S.HDL.L												
./garfield-v2-GCcorrection.sh	S.HDL.P	S.HDL.P												
./garfield-v2-GCcorrection.sh	S.HDL.TG	S.HDL.TG												
./garfield-v2-GCcorrection.sh	S.LDL.C	S.LDL.C												
./garfield-v2-GCcorrection.sh	S.LDL.L	S.LDL.L												
./garfield-v2-GCcorrection.sh	S.LDL.P	S.LDL.P												
./garfield-v2-GCcorrection.sh	S.VLDL.C	S.VLDL.C												
./garfield-v2-GCcorrection.sh	S.VLDL.FC	S.VLDL.FC												
./garfield-v2-GCcorrection.sh	S.VLDL.L	S.VLDL.L												
./garfield-v2-GCcorrection.sh	S.VLDL.P	S.VLDL.P												
./garfield-v2-GCcorrection.sh	S.VLDL.PL	S.VLDL.PL												
./garfield-v2-GCcorrection.sh	S.VLDL.TG	S.VLDL.TG												
./garfield-v2-GCcorrection.sh	Serum.C	Serum.C												
./garfield-v2-GCcorrection.sh	Serum.TG	Serum.TG												
./garfield-v2-GCcorrection.sh	SleepDuration	SleepDuration												
./garfield-v2-GCcorrection.sh	SM	SM												
./garfield-v2-GCcorrection.sh	SWB	SWB												
./garfield-v2-GCcorrection.sh	T2Diabetes	T2Diabetes												
./garfield-v2-GCcorrection.sh	T2Diabetes	T2Diabetes												
./garfield-v2-GCcorrection.sh	T2Diabetes_2012DEC17	T2Diabetes_2012DEC17												
./garfield-v2-GCcorrection.sh	T2Diabetes_Metabochip	T2Diabetes_Metabochip												
./garfield-v2-GCcorrection.sh	Tanner_females	Tanner_females												
./garfield-v2-GCcorrection.sh	Tanner_male_females_combined	Tanner_male_females_combined												
./garfield-v2-GCcorrection.sh	Tanner_males	Tanner_males												
./garfield-v2-GCcorrection.sh	TC	TC												
./garfield-v2-GCcorrection.sh	TG	TG												
./garfield-v2-GCcorrection.sh	Tot.FA	Tot.FA												
./garfield-v2-GCcorrection.sh	TotPG	TotPG												
./garfield-v2-GCcorrection.sh	Tyr	Tyr												
./garfield-v2-GCcorrection.sh	UACR_overall	UACR_overall												
./garfield-v2-GCcorrection.sh	Urea	Urea												
./garfield-v2-GCcorrection.sh	Val	Val												
./garfield-v2-GCcorrection.sh	VLDL.D	VLDL.D												
./garfield-v2-GCcorrection.sh	WC	WC												
./garfield-v2-GCcorrection.sh	WCadjBMI	WCadjBMI												
./garfield-v2-GCcorrection.sh	WHR	WHR												
./garfield-v2-GCcorrection.sh	WHRadjBMI	WHRadjBMI												
./garfield-v2-GCcorrection.sh	XL.HDL.C	XL.HDL.C												
./garfield-v2-GCcorrection.sh	XL.HDL.CE	XL.HDL.CE												
./garfield-v2-GCcorrection.sh	XL.HDL.FC	XL.HDL.FC												
./garfield-v2-GCcorrection.sh	XL.HDL.L	XL.HDL.L												
./garfield-v2-GCcorrection.sh	XL.HDL.P	XL.HDL.P												
./garfield-v2-GCcorrection.sh	XL.HDL.PL	XL.HDL.PL												
./garfield-v2-GCcorrection.sh	XL.HDL.TG	XL.HDL.TG												
./garfield-v2-GCcorrection.sh	XL.VLDL.L	XL.VLDL.L												
./garfield-v2-GCcorrection.sh	XL.VLDL.P	XL.VLDL.P												
./garfield-v2-GCcorrection.sh	XL.VLDL.PL	XL.VLDL.PL												
./garfield-v2-GCcorrection.sh	XL.VLDL.TG	XL.VLDL.TG												
./garfield-v2-GCcorrection.sh	XS.VLDL.L	XS.VLDL.L												
./garfield-v2-GCcorrection.sh	XS.VLDL.P	XS.VLDL.P												
./garfield-v2-GCcorrection.sh	XS.VLDL.PL	XS.VLDL.PL												
./garfield-v2-GCcorrection.sh	XS.VLDL.TG	XS.VLDL.TG												
./garfield-v2-GCcorrection.sh	XXL.VLDL.L	XXL.VLDL.L												
./garfield-v2-GCcorrection.sh	XXL.VLDL.P	XXL.VLDL.P												
./garfield-v2-GCcorrection.sh	XXL.VLDL.PL	XXL.VLDL.PL												
./garfield-v2-GCcorrection.sh	XXL.VLDL.TG	XXL.VLDL.TG												
														
